/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/CollableGlasses3.0.glb --transform 
Files: public/CollableGlasses3.0.glb [325.74KB] > /Users/nickgunning/Library/CloudStorage/GoogleDrive-nickgunning7@gmail.com/My Drive/Portfolio/CollableGlasses3.0-transformed.glb [41.72KB] (87%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/CollableGlasses3.0-transformed.glb");
  return (
    <group {...props} dispose={null} rotation={[0, Math.PI, 0]}>
      <mesh
        geometry={nodes.Circle019.geometry}
        material={nodes.Circle019.material}
        position={[-0.014, 0.215, 0.491]}
        rotation={[-Math.PI, 1.57, -2.76]}
        scale={[1.027, 1.027, 0.961]}
      >
        <meshStandardMaterial
          color="white"
          roughness={0.15}
          metalness={0.5}
          envMapIntensity={1}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/CollableGlasses3.0-transformed.glb");
